server:
  port: 8080
app:
  download-path: downloads/
  upload-path: uploads/

logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: logs/project.log
  level:
    com.abujava.*: DEBUG
    org.springframework.web: ERROR